import os

CMC_API = os.getenv("CMC_API")
BINANCE_KEY = os.getenv("BINANCE_KEY")
BINANCE_SECRET = os.getenv("BINANCE_SECRET")

VALOR_COMPRA = 10
MAX_TRADES = 2

TAKE_PROFIT = 1.03
STOP_LOSS = 0.985
TRAILING = 0.01
