services:
  - type: worker
    name: binance-trading-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_SECRET_KEY
        sync: false
      - key: MODO_TESTE
        value: "True"
      - key: VALOR_COMPRA
        value: "50"
      - key: TAKE_PROFIT
        value: "1.05"
      - key: STOP_LOSS
        value: "0.98"
      - key: PYTHON_VERSION
        value: "3.11.8"